version: '3.8'

services:
  client:
    build: ./client
    container_name: nextjs_app
    restart: always
    expose:
      - 3000

  server:
    build: ./server
    container_name: nestjs_app
    restart: always
    expose:
      - 4000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./nginx/ssl:/etc/letsencrypt
    depends_on:
      - client
      - server

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./nginx/ssl:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email igoscheff@gmail.com --agree-tos --no-eff-email -d blow.ru
